#!/usr/bin/env bash
# A script that configures ufw firewall to block all incoming traffic
# with the exception of ports 22, 443 and 80.

# Install ufw
apt-get install ufw

# Allow ufw to accept IPv6 traffic
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw

# Reload ufw
ufw disable
ufw enable

# Block all incoming traffic
ufw default deny incoming
ufw default allow outgoing

# Allow TCP 22, 443 and 80
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
